version: '2'
services:
  web:
    container_name: dylan-docker
    build: .
    ports: 
    - "80:3000"
    links:
    - mongo
  mongo: 
    container_name: mongo
    image: mongo
    ports:
    - '27017:27017'
